export declare const FLAG_KUBEVIRT_DYNAMIC = "KUBEVIRT_DYNAMIC";
export declare const FLAG_KUBEVIRT_CDI = "KUBEVIRT_CDI";
export declare const FLAG_CONSOLE_CLI_DOWNLOAD = "CONSOLE_CLI_DOWNLOAD";
export declare const FLAG_KUBEVIRT_PREFERENCES = "KUBEVIRT_PREFERENCES";
export declare const FLAG_KUBEVIRT_INSTANCETYPES = "KUBEVIRT_INSTANCETYPES";
