export var FLAG_KUBEVIRT_DYNAMIC = 'KUBEVIRT_DYNAMIC';
export var FLAG_KUBEVIRT_CDI = 'KUBEVIRT_CDI';
export var FLAG_CONSOLE_CLI_DOWNLOAD = 'CONSOLE_CLI_DOWNLOAD';
export var FLAG_KUBEVIRT_PREFERENCES = 'KUBEVIRT_PREFERENCES';
export var FLAG_KUBEVIRT_INSTANCETYPES = 'KUBEVIRT_INSTANCETYPES';
//# sourceMappingURL=consts.js.map