export declare const OTHER: any;
export declare const CONTAINER_EPHERMAL: any;
export declare const DYNAMIC: any;
export declare const DISKTYPE_SELECT_FIELDID = "disk-type-select";
export declare const STORAGECLASS_SELECT_FIELDID = "storage-class-select";
export declare const ACCESS_MODE_FIELDID = "access-mode";
export declare const VOLUMEMODE_FIELDID = "volume-mode";
export declare const ENABLE_PREALLOCATION_FIELDID = "enable-preallocation";
export declare const EXPAND_PVC_SIZE = "expandPVCSize";
export declare const SHARABLE_FIELD = "disk.shareable";
export declare const LUN_RESERVATION_FIELD = "disk.lun.reservation";
export declare const DATAVOLUME_PVC_NAME = "dataVolumeTemplate.spec.source.pvc.name";
export declare const DATAVOLUME_PVC_NAMESPACE = "dataVolumeTemplate.spec.source.pvc.namespace";
export declare const DATAVOLUME_SNAPSHOT_NAME = "dataVolumeTemplate.spec.source.snapshot.name";
export declare const DATAVOLUME_SNAPSHOT_NAMESPACE = "dataVolumeTemplate.spec.source.snapshot.namespace";
export declare const DATAVOLUME_HTTPURL_FIELD = "dataVolumeTemplate.spec.source.http.url";
export declare const IS_BOOT_SOURCE_FIELD = "isBootSource";
export declare const DISK_TYPE_FIELD = "diskType";
export declare const DISK_NAME_FIELD = "disk.name";
export declare const VOLUME_NAME_FIELD = "volume.name";
export declare const DISK_SIZE_FIELD = "dataVolumeTemplate.spec.storage.resources.requests.storage";
export declare const UPLOAD_FILENAME_FIELD = "uploadFile.filename";
export declare const UPLOAD_FILE_FIELD = "uploadFile.file";
export declare const STORAGE_CLASS_FIELD = "dataVolumeTemplate.spec.storage.storageClassName";
export declare const STORAGE_CLASS_PROVIDER_FIELD = "storageClassProvisioner";
export declare const ENALBE_PREACCLOCATION_FIELD = "dataVolumeTemplate.spec.preallocation";
export declare const ACCESS_MODE_FIELD = "dataVolumeTemplate.spec.storage.accessModes";
export declare const STORAGE_PROFILE_SETTINGS_APPLIED_FIELD = "storageProfileSettingsApplied";
export declare const VOLUME_MODE_FIELD = "dataVolumeTemplate.spec.storage.volumeMode";
export declare const DATAVOLUME_TEMPLATE_STORAGE = "dataVolumeTemplate.spec.storage";
export declare const CONTAINERDISK_IMAGE_FIELD = "volume.containerDisk.image";
export declare const PVC_CLAIMNAME_FIELD = "volume.persistentVolumeClaim.claimName";
export declare const REGISTRYURL_DATAVOLUME_FIELD = "dataVolumeTemplate.spec.source.registry.url";
