import { V1VirtualMachine, V1VirtualMachineInstance, V1Volume } from '@kubevirt-ui/kubevirt-api/kubevirt';
import { PendingChange } from './types';
export declare const checkCPUMemoryChanged: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const checkBootOrderChanged: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const checkBootModeChanged: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedEnvDisks: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => string[];
export declare const getInterfaceByName: (name: string, vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => any;
export declare const getChangedNICs: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => string[];
export declare const hasPendingChange: (pendingChange: PendingChange[]) => boolean;
export declare const nonHotPlugNICChangesExist: (pendingChanges: PendingChange[], nonHotPlugNICsExist: boolean) => boolean;
export declare const getSortedNICs: (changedNICs: string[], vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => {
    hotPlugNICs: string[];
    nonHotPlugNICs: string[];
};
export declare const getChangedGPUDevices: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => string[];
export declare const getChangedHostDevices: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => string[];
export declare const getChangedVolumesHotplug: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => V1Volume[];
export declare const getChangedDedicatedResources: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance, currentSelection: boolean) => boolean;
export declare const getChangedEvictionStrategy: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance, clusterEvictionStrategy: string) => boolean;
export declare const getChangedStartStrategy: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedHostname: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedNodeSelector: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedTolerations: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedAffinity: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedDescheduler: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance, currentSelection: boolean) => boolean;
export declare const getChangedCloudInit: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedAuthorizedSSHKey: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedGuestSystemAccessLog: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getChangedHeadlessMode: (vm: V1VirtualMachine, vmi: V1VirtualMachineInstance) => boolean;
export declare const getTabURL: (vm: V1VirtualMachine, tab: string) => string;
export declare const getPendingChangesByTab: (pendingChanges: PendingChange[]) => {
    pendingChangesDetailsTab: PendingChange[];
    pendingChangesDisksTab: PendingChange[];
    pendingChangesEnvTab: PendingChange[];
    pendingChangesNICsTab: PendingChange[];
    pendingChangesSchedulingTab: PendingChange[];
    pendingChangesScriptsTab: PendingChange[];
};
export declare const restartRequired: (vm: V1VirtualMachine) => boolean;
