export var DEFAULT_RDP_PORT = 3389;
export var TEMPLATE_VM_NAME_LABEL = 'vm.kubevirt.io/name';
export var DEFAULT_VV_FILENAME = 'console.vv';
export var DEFAULT_VV_MIMETYPE = 'application/x-virt-viewer';
export var DEFAULT_RDP_FILENAME = 'console.rdp';
export var DEFAULT_RDP_MIMETYPE = 'application/rdp';
export var VMI_LABEL_AS_RDP_SERVICE_SELECTOR = 'vm.kubevirt.io/name';
export var NODE_PORTS_LINK = 'https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/networking/configuring-ingress-cluster-traffic#nw-using-nodeport_configuring-ingress-cluster-traffic-nodeport';
export var POD = 'POD';
export var MULTUS = 'MULTUS';
//# sourceMappingURL=constants.js.map