export var DEFAULT_PREFERENCE_LABEL = 'instancetype.kubevirt.io/default-preference';
export var DEFAULT_INSTANCETYPE_LABEL = 'instancetype.kubevirt.io/default-instancetype';
export var COMMON_INSTANCETYPES = 'common-instancetypes';
export var INSTANCETYPE_CLASS_ANNOTATION = 'instancetype.kubevirt.io/class';
export var KUBEVIRT_ISO_LABEL = 'kubevirt.io/iso';
export var ISO = 'ISO';
export var deprecatedOSNames = ['centos-stream8', 'centos7'];
export var HIDE_DEPRECATED_BOOTABLE_VOLUMES = 'hideDeprecatedBootableVolumes';
export var HIDE_DEPRECATED_BOOTABLE_VOLUMES_LABEL = 'Hide deprecated bootable volumes';
//# sourceMappingURL=constants.js.map