export var CLOUD = 'cloud';
export var CLOUD_CONFIG_HEADER = '#cloud-config';
export var ACTIVATION_KEY = 'activation-key';
export var SERVER_URL_KEY = 'server-url';
export var ORG_KEY = 'org';
export var RH_SUBSCRIPTION_KEY = 'rh_subscription';
export var AUTO_UPDATE_OS_CMD = 'systemctl enable --now dnf-automatic-install.timer';
export var DNF_AUTOMATIC_PACKAGE = 'dnf-automatic';
//# sourceMappingURL=constants.js.map