export var PARAMETER_VALUE_TYPES;
(function (PARAMETER_VALUE_TYPES) {
    PARAMETER_VALUE_TYPES["GENERATED"] = "GENERATED";
    PARAMETER_VALUE_TYPES["NONE"] = "NONE";
    PARAMETER_VALUE_TYPES["VALUE"] = "VALUE";
})(PARAMETER_VALUE_TYPES || (PARAMETER_VALUE_TYPES = {}));
//# sourceMappingURL=constants.js.map